### ISSUE TITLE
not really an issue but remove "use redemrp"

### ISSUE THREAD

**Issue by JordanPANDA** [RedEM-RP/redem_roleplay#23]
i wanted to suggest disabling the "use redemrp" in the db import since we don't all use this DB name (not hard to bypass this problem but well it cost nothing to try) :)

**Comment by kvarela09** [comment]
I get this error in console, I do not know what causes it, in principle everything is fine, / setmoney, / setxp, / addmney, / setmoney ... but if the error comes out it is probably something I have not tried yet. I get it since I installed 0.1.0
------------------------------------------------------------------------------------------------------------
SCRIPT ERROR: @redem_roleplay/server/sv_player.lua:138: attempt to compare nil with number
> ref (@redem_roleplay/server/sv_player.lua:138)
> cb (@redemrp_gameplay/server/players.lua:72)
> ref (@redemrp_gameplay/server/_helpers.lua:57)
> handler (@redem_roleplay/server/sv_main.lua:81)
> GetCharacter (@redemrp_gameplay/server/_helpers.lua:56)
> BonusXP (@redemrp_gameplay/server/players.lua:62)
> packetHandler (@redemrp_gameplay/server/players.lua:23)
> handler (@redemrp_gameplay/server/_helpers.lua:10)
--------------------------------------------------------------------------------------------------------------

**Comment by kanersps** [comment]
A PR could work. Currently fairly busy to change this real quick, as my local branch would be off. If there isn’t a pr for it in a week or so I’ll do it manually :)
